// <auto-generated> by Tools/BookUi/build_title_logo_anim.py - do not edit by hand. </auto-generated>
namespace AlloyClient.Screens.Components;

public static class TitleLogoAnimData {
    public const string SheetPath = "Title/LogoSheet.png";
    public const int SheetWidth = 2816;
    public const int SheetHeight = 3520;
    public const int FrameWidth = 352;
    public const int FrameHeight = 440;
    public const int Columns = 8;
    public const int FrameCount = 62;

    // Frame rate of the stored frames (the source clip is 24 fps, every 2nd frame is kept).
    public const float SourceFps = 12.0f;
}
