// <auto-generated> by Tools/BookUi/build_title_cave.py - do not edit by hand. </auto-generated>
namespace WaWClient.Screens.Components;

internal static class CaveBackdropData {
    public const int MapWidth = 1280;
    public const int MapHeight = 720;
    public const int SheetWidth = 1280;
    public const int SheetHeight = 816;
    public const int GlowSize = 96;

    // Sprite index in the glow strip: 0 teal, 1 green, 2 amber, 3 purple, 4 white, 5 fog.
    // Glow(kind, centre x, centre y, drawn size, base alpha, alpha swing, period ms, phase 0..1, flicker)
    internal readonly record struct Glow(int Kind, int X, int Y, int Size, float Base, float Swing, float PeriodMs, float Phase, bool Flicker);
    internal static readonly Glow[] Glows = [
        new(1, 314, 211, 150, 0.10f, 0.12f, 4520f, 0.94f, false),
        new(0, 568, 458, 150, 0.10f, 0.12f, 5153f, 0.45f, false),
        new(1, 1063, 491, 150, 0.10f, 0.12f, 4386f, 0.71f, false),
        new(0, 125, 508, 150, 0.10f, 0.12f, 4306f, 0.84f, false),
        new(3, 365, 77, 70, 0.05f, 0.07f, 6348f, 0.54f, false),
        new(3, 756, 97, 70, 0.05f, 0.07f, 5471f, 0.79f, false),
        new(3, 125, 111, 70, 0.05f, 0.07f, 6109f, 0.91f, false),
        new(3, 1171, 264, 70, 0.05f, 0.07f, 4596f, 0.93f, false),
        new(3, 133, 421, 70, 0.05f, 0.07f, 4650f, 0.86f, false),
        new(3, 1172, 625, 70, 0.05f, 0.07f, 4894f, 0.34f, false),
        new(3, 985, 641, 70, 0.05f, 0.07f, 5597f, 0.75f, false),
        new(0, 610, 241, 240, 0.05f, 0.05f, 6000f, 0.3f, false),
    ];

    // Mist(centre x, centre y, width, height, base alpha, alpha swing, period ms, phase)
    internal readonly record struct Mist(int X, int Y, int Width, int Height, float Base, float Swing, float PeriodMs, float Phase);
    internal static readonly Mist[] Mists = [
        new(270, 385, 576, 277, 0.10f, 0.10f, 9710f, 0.00f),
        new(820, 437, 566, 257, 0.10f, 0.10f, 9436f, 0.20f),
        new(671, 424, 501, 241, 0.10f, 0.10f, 9228f, 0.40f),
        new(1079, 285, 445, 256, 0.10f, 0.10f, 11745f, 0.60f),
        new(197, 431, 506, 321, 0.10f, 0.10f, 14525f, 0.80f),
    ];

    // Places a spore / firefly can twinkle: around the crystals, the mushrooms and the water, plus scattered floor.
    internal static readonly (int X, int Y)[] SporeSpots = [
        (311, 165),
        (357, 236),
        (360, 243),
        (293, 208),
        (255, 226),
        (299, 245),
        (618, 418),
        (615, 446),
        (549, 434),
        (582, 463),
        (565, 453),
        (620, 475),
        (1094, 516),
        (1063, 494),
        (1007, 479),
        (1050, 483),
        (1048, 483),
        (1020, 485),
        (185, 477),
        (144, 489),
        (135, 498),
        (177, 458),
        (113, 467),
        (183, 546),
        (404, 65),
        (366, 72),
        (360, 92),
        (732, 112),
        (796, 84),
        (765, 111),
        (94, 73),
        (156, 117),
        (112, 125),
        (1149, 230),
        (1207, 224),
        (1211, 252),
        (157, 414),
        (172, 401),
        (154, 402),
        (1189, 634),
        (1154, 620),
        (1144, 639),
        (974, 623),
        (965, 605),
        (975, 640),
        (846, 553),
        (282, 376),
        (598, 504),
        (897, 423),
        (383, 75),
        (1143, 243),
        (503, 347),
        (1167, 182),
        (822, 386),
        (237, 347),
        (932, 151),
        (259, 557),
        (944, 572),
        (699, 548),
        (1140, 300),
        (1198, 603),
        (363, 140),
        (564, 364),
        (618, 470),
        (749, 560),
        (913, 188),
        (849, 489),
        (566, 501),
        (550, 520),
        (690, 561),
        (1230, 509),
        (242, 201),
        (688, 218),
        (787, 121),
        (620, 643),
    ];

    // Pond glints: small light flecks on the water surface.
    internal static readonly (int X, int Y)[] PondGlints = [
        (584, 220),
        (626, 205),
        (588, 219),
        (634, 273),
        (650, 286),
        (646, 276),
        (603, 241),
        (596, 209),
        (653, 207),
        (617, 290),
        (594, 242),
        (559, 248),
        (600, 251),
        (635, 290),
    ];
}
