// Emits web/shim/Enums.g.cs: copies (same names, same values) of the OpenTK.Graphics.OpenGL / OpenTK.Platform enums the client sources
// actually use, so the browser build compiles against identical enum types without the native OpenTK assemblies.
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

var srcRoots = args.Take(args.Length - 1).ToArray();
var outFile = args[^1];
var src = new StringBuilder();
foreach (var root in srcRoots)
    foreach (var f in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
        { var nf = f.Replace((char)92, (char)47); if (!nf.Contains("/obj/") && !nf.Contains("/bin/") && !nf.Contains("GameWindow.cs")) src.AppendLine(File.ReadAllText(f)); }
var text = src.ToString();
var words = new HashSet<string>(Regex.Matches(text, @"[A-Za-z_][A-Za-z0-9_]*").Select(m => m.Value));

var full = new HashSet<string> { "Key", "Scancode", "MouseButton", "MouseButtonFlags", "WindowMode", "CursorMode", "ClipboardFormat", "MessageBoxType" };
var asms = new[] { typeof(OpenTK.Graphics.OpenGL.GL).Assembly, typeof(OpenTK.Platform.Toolkit).Assembly };
var wantedNs = new HashSet<string> { "OpenTK.Graphics.OpenGL", "OpenTK.Platform", "OpenTK.Graphics" };
var sb = new StringBuilder("// <auto-generated> by tools/enumgen - do not edit\n#pragma warning disable\nusing System;\n\n");
var seen = new HashSet<string>();
foreach (var t in asms.SelectMany(a => a.GetTypes()).Where(t => t.IsEnum && t.IsPublic && wantedNs.Contains(t.Namespace ?? "")).OrderBy(t => t.Namespace).ThenBy(t => t.Name)) {
    if (!words.Contains(t.Name) || !seen.Add(t.Namespace + "." + t.Name)) continue;
    var names = Enum.GetNames(t);
    var keep = full.Contains(t.Name) || names.Length <= 80 ? names : names.Where(n => words.Contains(n)).ToArray();
    if (keep.Length == 0) keep = names.Take(1).ToArray();
    var under = Enum.GetUnderlyingType(t);
    var typeName = under == typeof(int) ? "int" : under == typeof(uint) ? "uint" : under == typeof(byte) ? "byte" : under == typeof(ushort) ? "ushort" : under == typeof(long) ? "long" : under == typeof(short) ? "short" : "int";
    sb.Append($"namespace {t.Namespace} {{\n");
    if (t.GetCustomAttribute<FlagsAttribute>() != null) sb.Append("    [Flags]\n");
    sb.Append($"    public enum {t.Name} : {typeName} {{\n");
    var done = new HashSet<string>();
    foreach (var n in keep) {
        if (!done.Add(n)) continue;
        var v = Convert.ToInt64(Enum.Parse(t, n));
        var lit = under == typeof(uint) || under == typeof(ulong) ? $"unchecked(({typeName}){v}u)" : v.ToString();
        sb.Append($"        {n} = {lit},\n");
    }
    sb.Append("    }\n}\n\n");
}
File.WriteAllText(outFile, sb.ToString());
Console.WriteLine($"wrote {outFile}: {seen.Count} enums");
