// <auto-generated> by Tools/BookUi/build_backdrop_ground.py - do not edit by hand.
namespace AlloyClient.Screens.Components.CharacterList;

internal static class BackdropData {
    // Sheet/Index = the decor cell (SmallPlants/MediumPlants/SmallTrees/MediumTrees); Base = where it stands (1280x720 design px); Width/Height = drawn cell size;
    // InsetPx = how far the cell bottom hangs below the base (per-object BottomInset).
    internal readonly record struct Decor(string Sheet, int Index, int BaseX, int BaseY, int Width, int Height, int InsetPx, bool Sway);

    internal static readonly Decor[] Items = [
        new("mediumTrees", 0, 62, 168, 120, 180, 12, true),
        new("mediumPlants", 1, 26, 200, 60, 90, 6, true),
        new("mediumTrees", 1, 150, 92, 120, 180, 12, true),
        new("mediumPlants", 4, 66, 338, 60, 90, 6, false),
        new("mediumPlants", 3, 30, 392, 60, 90, 5, false),
        new("mediumPlants", 6, 96, 500, 60, 90, 7, false),
        new("mediumPlants", 3, 44, 566, 60, 90, 5, false),
        new("mediumPlants", 5, 112, 676, 60, 90, 5, false),
        new("mediumPlants", 5, 64, 662, 60, 90, 5, false),
        new("mediumPlants", 0, 150, 690, 60, 90, 5, true),
        new("mediumTrees", 1, 1236, 248, 120, 180, 12, true),
        new("smallTrees", 0, 1176, 214, 84, 126, 11, true),
        new("mediumPlants", 2, 1196, 262, 60, 90, 6, true),
        new("mediumPlants", 4, 1230, 402, 60, 90, 6, false),
        new("mediumPlants", 3, 1252, 470, 60, 90, 5, false),
        new("smallPlants", 2, 1196, 330, 36, 54, 5, false),
        new("smallTrees", 1, 1262, 610, 84, 126, 11, true),
        new("mediumPlants", 1, 1240, 696, 60, 90, 6, true),
        new("smallPlants", 3, 640, 30, 36, 54, 5, false),
        new("smallPlants", 0, 700, 44, 36, 54, 5, false),
        new("smallPlants", 2, 420, 24, 36, 54, 5, false),
        new("smallPlants", 3, 880, 700, 36, 54, 5, false),
        new("smallPlants", 1, 560, 706, 36, 54, 5, false),
    ];
}
