// <auto-generated> by Tools/BookUi/build_backdrop_ground.py - do not edit by hand.
namespace AlloyClient.Screens.Components.CharacterList;

internal static class BackdropData {
    // Index = ForestDecor sheet cell; Base = where it stands (1280x720 design px); Width/Height = drawn cell size;
    // InsetPx = how far the cell bottom hangs below the base (per-object BottomInset).
    internal readonly record struct Decor(int Index, int BaseX, int BaseY, int Width, int Height, int InsetPx, bool Sway);

    internal static readonly Decor[] Items = [
        new(0, 62, 168, 120, 180, 12, true),
        new(2, 26, 200, 120, 180, 6, true),
        new(11, 150, 92, 120, 180, 12, true),
        new(7, 66, 338, 120, 180, 6, false),
        new(14, 30, 392, 120, 180, 5, false),
        new(15, 96, 500, 120, 180, 7, false),
        new(14, 44, 566, 120, 180, 5, false),
        new(5, 112, 676, 120, 180, 5, false),
        new(5, 64, 662, 120, 180, 5, false),
        new(3, 150, 690, 120, 180, 5, true),
        new(11, 1236, 248, 120, 180, 12, true),
        new(1, 1176, 214, 120, 180, 11, true),
        new(13, 1196, 262, 120, 180, 6, true),
        new(7, 1230, 402, 120, 180, 6, false),
        new(14, 1252, 470, 120, 180, 5, false),
        new(10, 1196, 330, 120, 180, 5, false),
        new(12, 1262, 610, 120, 180, 11, true),
        new(2, 1240, 696, 120, 180, 6, true),
        new(6, 640, 30, 120, 180, 5, false),
        new(8, 700, 44, 120, 180, 5, false),
        new(10, 420, 24, 120, 180, 5, false),
        new(6, 880, 700, 120, 180, 5, false),
        new(9, 560, 706, 120, 180, 5, false),
    ];
}
