// <auto-generated> by Tools/BookUi/build_book_assets.py - do not edit by hand.
namespace AlloyClient.Screens.Components.CharacterList;

// Coordinates are in the book's native pixels, relative to the static open book's top-left corner.
internal static class BookFrameData {
    internal readonly record struct Frame(int X, int Y, int W, int H);

    internal const int BookWidth = 672;
    internal const int BookHeight = 416;

    // Open animation frames Open/1..N (the last state is the static book itself).
    internal static readonly Frame[] Open = [
        new(336, -5, 341, 421),
        new(336, -5, 341, 421),
        new(336, -25, 410, 441),
        new(330, -94, 384, 510),
        new(-4, -96, 676, 512),
    ];

    // Page-flip patches FlipL/1..N (turning to the NEXT page) and FlipR/1..N (PREVIOUS page), drawn over the static book.
    internal static readonly Frame[] FlipLeft = [
        new(350, -4, 265, 399),
        new(344, -24, 143, 425),
        new(266, -15, 49, 427),
        new(95, -12, 228, 406),
        new(15, 288, 110, 107),
        new(15, 311, 95, 84),
        new(15, 344, 51, 48),
    ];
    internal static readonly Frame[] FlipRight = [
        new(58, -4, 265, 399),
        new(186, -24, 143, 425),
        new(358, -15, 49, 427),
        new(350, -12, 228, 406),
        new(548, 288, 110, 107),
        new(563, 311, 95, 84),
        new(607, 344, 51, 48),
    ];

    // Side tabs Tab1..Tab6, top to bottom: the shared box of the Idle/Active sprites.
    internal static readonly Frame[] Tabs = [
        new(-12, 72, 43, 37),
        new(-12, 120, 43, 37),
        new(-12, 168, 43, 37),
        new(-12, 216, 43, 37),
        new(-12, 264, 43, 37),
        new(-12, 312, 43, 37),
        new(-12, 360, 43, 37),     // Tab7 (FAST TRAVEL): not in the pack - Tab6's art one slot lower, see Tools/BookUi/build_fast_travel.py
    ];

    // Vertical extent (native px) of each tab's idle body.
    internal static readonly (int Top, int Bottom)[] TabBands = [
        (72, 109),
        (120, 157),
        (168, 205),
        (216, 253),
        (264, 301),
        (312, 349),
        (360, 397),
    ];

    // Tab face centre (sprite-local native px) and the tab icons true native sizes, in tab order.
    internal const float TabFaceCenterX = 14.0f;
    internal const float TabFaceCenterY = 16.5f;
    internal static readonly (int W, int H)[] TabIconSizes = [
        (16, 16),
        (16, 16),
        (16, 16),
        (16, 16),
        (16, 16),
        (16, 16),
        (16, 16),
    ];
}
