using System;
using System.Collections.Generic;
using AlloyClient.Assets.Libraries;
using AlloyClient.Core;
using AlloyClient.Data;
using AlloyClient.Ui;
using AlloyClient.Utils;
using Alloy.UiLib.BuiltIn;
using Alloy.UiLib.Core;
using Alloy.UiLib.Extra;
using OpenTK.Mathematics;

namespace AlloyClient.Screens.Components.CharacterList;

// The character-select "book" (replaces CharacterConsole) - the open book from the "Pocket Inventory
// Series #7 Gems of Status" pack (Desktop/GUI), mostly filling the screen and slightly transparent
// so the forest backdrop shows through. It opens on the Profile page and has six side tabs (icons
// from Desktop/CharacterSelectionPageIcons): Profile, Characters, Graveyard, Inbox, Daily Spin and
// Daily Gift. Only Profile and Characters have real content so far - the other four are "coming
// soon" pages until those features exist. Character creation is NOT a page: the Characters page's
// "new character" tile opens the creation popup (ClassContainer), a wooden frame that sits over the book.
//
// Art layout comes from BookFrameData.g.cs, generated by Tools/BookUi/build_book_assets.py: every
// pack frame shares one canvas, so all positions below are the book's native pixels (relative to
// the static open book's top-left) times BookScale. The page-flip frames are small patches drawn
// over the static book, and the same table covers the open animation and the six tab sprites.
//
// All timing is driven by one EnterFrame accumulator (not Timers) - a Timer created from inside
// another Timer's callback has proven unreliable elsewhere in this UI (see BookOverlay).
public sealed partial class CharacterBook : Container {

    // 672x416 native -> ~1075x666 of the 1280x720 design canvas ("mostly fills the screen"). Not an
    // integer scale, like most sprites in this game.
    private const float BookScale = 1.6f;

    // The opened book is centred on the screen's true centre (x = 640 of the 1280 canvas): its 672px native
    // width * 1.6 = 1075px, so it starts 102px in. The opening frames sit at their own native positions (the spine
    // and the bottom edge stay put, as the art was drawn) plus one smooth sideways slide (see PlaceBookFrame) that
    // starts with the closed book centred on the screen and ends with the open book centred.
    private const int ScreenCenterX = 640;
    private const int BookLeft = ScreenCenterX - 538;
    private const int BookTop = 27;

    // Slightly see-through at rest, per request, so the forest shows through the pages.
    private const float IdleAlpha = 0.93f;

    // Page text areas, native px (inside the pages' own decorative border), and the spine.
    private const int LeftPageNativeLeft = 44;
    private const int LeftPageNativeRight = 298;
    private const int RightPageNativeLeft = 378;
    private const int RightPageNativeRight = 632;
    private const int PageNativeTop = 40;
    private const int PageNativeBottom = 364;

    private static int Px(int nativeX) => BookLeft + (int)MathF.Round(nativeX * BookScale);
    private static int Py(int nativeY) => BookTop + (int)MathF.Round(nativeY * BookScale);
    private static int Sz(int native) => (int)MathF.Round(native * BookScale);

    private static readonly int LeftPageX = Px(LeftPageNativeLeft);
    private static readonly int LeftPageW = Sz(LeftPageNativeRight - LeftPageNativeLeft);
    private static readonly int LeftPageCenterX = LeftPageX + LeftPageW / 2;
    private static readonly int RightPageX = Px(RightPageNativeLeft);
    private static readonly int RightPageW = Sz(RightPageNativeRight - RightPageNativeLeft);
    private static readonly int RightPageCenterX = RightPageX + RightPageW / 2;
    private static readonly int PageTop = Py(PageNativeTop);
    private static readonly int PageBottom = Py(PageNativeBottom);

    // Where the opening animation starts, sideways from the book's native spot (negative = left): the closed book sits
    // on the right half of the pack's canvas, so this pulls its centre back onto the screen's centre. It slides to 0
    // as the book opens.
    private static readonly int ClosedBookOffsetX =
        -(int) MathF.Round((BookFrameData.Open[0].X + BookFrameData.Open[0].W / 2f - BookFrameData.BookWidth / 2f) * BookScale);

    // Entrance: the closed book fades in, holds a short beat, opens frame by frame, then the tabs and the page
    // content settle in one after another. It starts the moment the screen appears - the title -> book hand-off
    // (LoaderFlows.FromTitleToCharacterList) is a short fade with no loader in front of it anymore, so there is no
    // extra waiting built in here.
    private const int InitialDelayMs = 0;
    private const int FadeInMs = 900;
    private const int HoldClosedMs = 250;
    private const int OpenMs = 1000;
    private const int TabStaggerMs = 110;
    private const int TabFadeMs = 300;
    private const int ContentFadeMs = 450;

    // Page flip: 7 patch frames.
    private const int FlipFrameMs = 42;
    private const int PageFadeMs = 160;

    private const uint Ink = 0x2A1C14;
    private const uint InkSoft = 0x6B4A33;
    private const uint Hover = 0x9C4A1A;
    private const uint TileSelected = 0xC79A5B;
    private const uint TileIdle = 0x8A6A4A;

    private const float TitleSize = 32f;
    private const float BodySize = 26f;
    private const float SmallSize = 20f;

    // The Graveyard page has no list behind it yet (nothing records a dead character), so it just says this.
    private const string GraveyardEmpty = "You haven't died yet.";

    // The page icons are 16x16 pixel art, drawn on the tabs at an exact 2x (not the book's 1.6x) so every art pixel stays a clean block.
    private const int TabIconScale = 2;

    // The PLAY button: a parchment scroll (the same piece and look as the character creation popup's buttons) with the label in the
    // book's ink. Both the Last Played and the Details page build it in one place, so it sits at the same spot on each.
    private const int PlayButtonWidth = 190;
    private const int PlayButtonHeight = 50;
    private const int PlayButtonBottomGap = 10;
    private static readonly ColorTransform ScrollHoverTint = new(0.86f, 0.8f, 0.7f, 1f);

    // The BACK button is the sign-in book's back icon (Icons/BookBackIcon, same size and hover as the Register / Sign In forms use).
    private const int BackIconWidth = 40;
    private const int BackIconHeight = 42;
    private const float BackIconHoverScale = 1.15f;

    // Every stat / readout / small label (the cards on the Characters page, the stats on the Last Played / Details pages, the
    // profile stat list) is set in BitPotion, the client's small-text pixel font.
    private const FontGroup CharacterFont = FontGroup.MyriadPro;

    private enum BookPage { Profile, Characters, Graveyard, Inbox, DailySpin, DailyGift }

    private static readonly string[] TabIcons = ["Profile", "Characters", "Graveyard", "Inbox", "DailySpin", "DailyGift"];

    private readonly Action<Character> _onPlay;
    private readonly Action _onForge;
    private readonly Action _onBack;

    private readonly ObjectRect _book;
    private readonly ObjectRect _bookBlend;     // the NEXT opening frame, dissolving in over _book
    private readonly ObjectRect _flip;
    private readonly Container[] _tabs = new Container[6];
    private readonly ObjectRect[] _tabSprites = new ObjectRect[6];
    private readonly ObjectRect[] _tabIcons = new ObjectRect[6];
    private readonly Container[] _pages = new Container[6];
    private readonly Container _backButton;

    private List<Character> _characters = [];
    private int _selectedIndex = -1;
    private int _gold;
    private int _fame;
    private readonly AccountData _account;
    private readonly string _accountName;

    private BookPage _currentPage = BookPage.Profile;
    private BookPage? _pendingPage;

    private double _elapsedMs;
    private bool _entranceComplete;
    private int _shownOpenFrame = -1;
    private int _shownBlendFrame = -1;

    private bool _flipping;
    private bool _flipForward;
    private double _flipElapsedMs;
    private int _flipShownFrame = -1;
    private BookPage _flipTarget;

    private double _pageFadeMs = PageFadeMs;

    public CharacterBook(Action<Character> onPlay, Action onForge, Action onBack) : base(new ContainerConfig { Width = 1280, Height = 720 }) {
        _onPlay = onPlay;
        _onForge = onForge;
        _onBack = onBack;
        _account = GlobalData.Get<AccountData>();
        _accountName = _account?.Name ?? "";

        _book = new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas("BookGems/Open/1", 0, false),
            OutlineEnabled = false,
            GlowEnabled = false
        });
        AddChild(_book);
        PlaceBookFrame(_book, ref _shownOpenFrame, 0, ClosedBookOffsetX);

        _bookBlend = new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas("BookGems/Open/2", 0, false),
            OutlineEnabled = false,
            GlowEnabled = false
        });
        _bookBlend.Visible = false;
        AddChild(_bookBlend);

        _flip = new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas("BookGems/FlipL/1", 0, false),
            OutlineEnabled = false,
            GlowEnabled = false
        });
        _flip.Visible = false;
        AddChild(_flip);

        for (var i = 0; i < 6; i++) {
            BuildTab(i);
        }

        for (var i = 0; i < 6; i++) {
            _pages[i] = new Container();
            _pages[i].Visible = false;
            AddChild(_pages[i]);
        }

        // Top-left corner of the left page, level with the page titles (and a touch further left than the old bottom-left spot).
        _backButton = BuildBackIconButton(Px(LeftPageNativeLeft - 4) + BackIconWidth / 2, PageTop + Sz(16), () => _onBack());
        _backButton.Visible = false;
        AddChild(_backButton);

        RebuildPages();
        RefreshRewards();

        Alpha = 0f;
        AddEventListener(Event.EnterFrame, OnFrame);
    }

    #region Public API (same shape the console had)

    public Character CurrentCharacter => _selectedIndex >= 0 && _selectedIndex < _characters.Count ? _characters[_selectedIndex] : null;

    public void SetCharacters(List<Character> characters, int selectIndex) {
        _characters = characters;
        _selectedIndex = characters.Count == 0 ? -1 : Math.Clamp(selectIndex, 0, characters.Count - 1);
        RebuildPages();
    }

    public void SetAccountInfo(int gold, int fame) {
        _gold = gold;
        _fame = fame;
        RebuildPages();
    }

    #endregion

    #region Tabs

    private void BuildTab(int index) {
        var frame = BookFrameData.Tabs[index];

        var tab = new Container { X = Px(frame.X), Y = Py(frame.Y) };
        tab.MouseEnabled = true;

        var sprite = new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas($"BookGems/Tab{index + 1}/Idle", 0, false),
            Width = Sz(frame.W),
            Height = Sz(frame.H),
            OutlineEnabled = false,
            GlowEnabled = false
        });
        tab.AddChild(sprite);

        // Icon centred on the tab's blue face (measured from the sprite, see BookFrameData.TabFaceCenter*) at its
        // true aspect ratio - the face sits above the tab's dark lip, so the tab's overall centre would be too low.
        var iconSize = BookFrameData.TabIconSizes[index];
        var icon = new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas($"BookGems/Icon/{TabIcons[index]}", 0, false),
            X = (int) MathF.Round(BookFrameData.TabFaceCenterX * BookScale),
            Y = (int) MathF.Round(BookFrameData.TabFaceCenterY * BookScale),
            Width = iconSize.W * TabIconScale,
            Height = iconSize.H * TabIconScale,
            Anchor = UiAnchor.Middle,
            OutlineEnabled = false,
            GlowEnabled = false
        });
        tab.AddChild(icon);

        var down = false;
        tab.AddEventListener(MouseEvent.MouseOver, () => SetTabLook(index, true));
        tab.AddEventListener(MouseEvent.MouseOut, () => SetTabLook(index, false));
        tab.AddEventListener(MouseEvent.LeftDown, () => down = true);
        tab.AddEventListener(MouseEvent.LeftUp, () => {
            if (down) {
                GoToPage((BookPage) index);
            }
            down = false;
        });

        tab.Visible = false;
        _tabs[index] = tab;
        _tabSprites[index] = sprite;
        _tabIcons[index] = icon;
        AddChild(tab);
    }

    // The current page's tab always shows its "pulled out" pennant; hovering another tab previews it.
    private void SetTabLook(int index, bool hovering) {
        var active = index == (int) (_flipping ? _flipTarget : _currentPage) || hovering;
        _tabSprites[index].ChangeTexture(TextureHelper.FromUiAtlas($"BookGems/Tab{index + 1}/{(active ? "Active" : "Idle")}", 0, false));
    }

    private void RefreshTabLooks() {
        for (var i = 0; i < 6; i++) {
            SetTabLook(i, false);
        }
    }

    #endregion

    #region Page navigation and flip

    private void GoToPage(BookPage page) {
        if (!_entranceComplete) {
            return;
        }

        if (_flipping) {
            _pendingPage = page;
            return;
        }

        if (page == _currentPage) {
            return;
        }

        StartFlip(page);
    }

    private void StartFlip(BookPage target) {
        if (target is BookPage.Inbox or BookPage.DailySpin or BookPage.DailyGift) {
            RefreshRewards();       // always show what the server says now
        }

        _flipping = true;
        _flipTarget = target;
        _flipForward = target > _currentPage;
        _flipElapsedMs = 0;
        _flipShownFrame = -1;
        _pages[(int) _currentPage].Visible = false;
        _backButton.Visible = false;
        RefreshTabLooks();
    }

    private void UpdateFlip(double dt) {
        _flipElapsedMs += dt;
        var frames = _flipForward ? BookFrameData.FlipLeft : BookFrameData.FlipRight;
        var index = (int) (_flipElapsedMs / FlipFrameMs);

        if (index >= frames.Length) {
            _flip.Visible = false;
            _flipping = false;
            _currentPage = _flipTarget;
            _pages[(int) _currentPage].Alpha = 0f;
            _pages[(int) _currentPage].Visible = true;
            _backButton.Visible = true;
            _pageFadeMs = 0;
            RefreshTabLooks();

            if (_pendingPage.HasValue) {
                var next = _pendingPage.Value;
                _pendingPage = null;
                if (next != _currentPage) {
                    StartFlip(next);
                }
            }
            return;
        }

        if (index != _flipShownFrame) {
            _flipShownFrame = index;
            var f = frames[index];
            _flip.ChangeTexture(TextureHelper.FromUiAtlas($"BookGems/Flip{(_flipForward ? "L" : "R")}/{index + 1}", 0, false));
            _flip.X = Px(f.X);
            _flip.Y = Py(f.Y);
            _flip.Resize(Sz(f.W), Sz(f.H));
            _flip.Visible = true;
        }
    }

    #endregion

    #region Frame loop / entrance

    private void OnFrame() {
        var dt = Stage.GameTime.ElapsedMs;
        UpdateRewards(dt);

        if (!_entranceComplete) {
            UpdateEntrance(dt);
        }

        if (_flipping) {
            UpdateFlip(dt);
        } else if (_entranceComplete && _pageFadeMs < PageFadeMs) {
            _pageFadeMs += dt;
            _pages[(int) _currentPage].Alpha = (float) Math.Clamp(_pageFadeMs / PageFadeMs, 0.0, 1.0);
        }
    }

    private void UpdateEntrance(double dt) {
        _elapsedMs += dt;
        var t = _elapsedMs;

        if (t <= InitialDelayMs) {
            Alpha = 0f;
            return;
        }

        var sinceDelay = t - InitialDelayMs;
        Alpha = sinceDelay < FadeInMs ? IdleAlpha * (float) (sinceDelay / FadeInMs) : IdleAlpha;

        var openStart = InitialDelayMs + FadeInMs + HoldClosedMs;
        if (t < openStart) {
            return;
        }

        var openProgress = (t - openStart) / OpenMs;
        if (openProgress < 1.0) {
            ShowOpening(openProgress);
            return;
        }

        ShowStaticBook();
        var sinceOpen = t - (openStart + OpenMs);

        for (var i = 0; i < 6; i++) {
            var local = sinceOpen - i * TabStaggerMs;
            var p = (float) Math.Clamp(local / TabFadeMs, 0.0, 1.0);
            _tabs[i].Visible = p > 0f;
            _tabs[i].Alpha = p;
            _tabs[i].X = Px(BookFrameData.Tabs[i].X) + (int) ((1f - p) * Sz(12));
        }

        var contentStart = 6 * TabStaggerMs;
        var page = _pages[(int) _currentPage];
        if (sinceOpen >= contentStart) {
            var p = (float) Math.Clamp((sinceOpen - contentStart) / ContentFadeMs, 0.0, 1.0);
            page.Visible = true;
            page.Alpha = p;
            _backButton.Visible = true;
            _backButton.Alpha = p;
        }

        if (sinceOpen >= contentStart + ContentFadeMs) {
            page.Alpha = 1f;
            _backButton.Alpha = 1f;
            _pageFadeMs = PageFadeMs;
            _entranceComplete = true;
            RefreshTabLooks();
        }
    }

    // The book opening, as one continuous motion instead of five hard frame swaps. The art is 5 drawn frames plus the
    // finished static book (index Open.Length); progress 0..1 (eased in and out) sweeps through them, and the frame
    // being left stays underneath while the next one dissolves in over it. Every frame keeps its native position
    // (spine and bottom edge fixed, as the pack drew them), and a single eased slide carries the whole thing from
    // "closed book centred" to "open book centred" - re-centring each frame on its own is what made the spine hop.
    private void ShowOpening(double progress) {
        var eased = 0.5 - 0.5 * Math.Cos(Math.PI * progress);
        var position = eased * BookFrameData.Open.Length;
        var from = Math.Min((int) position, BookFrameData.Open.Length - 1);
        var mix = (float) (position - from);
        var shift = (int) MathF.Round((1f - (float) eased) * ClosedBookOffsetX);

        PlaceBookFrame(_book, ref _shownOpenFrame, from, shift);
        PlaceBookFrame(_bookBlend, ref _shownBlendFrame, from + 1, shift);

        // The next frame dissolves in over the first half; only then does the old one fade out from underneath, so
        // the parts both frames share never go see-through in the middle of the swap.
        _bookBlend.Visible = mix > 0f;
        _bookBlend.Alpha = Math.Min(1f, mix * 2f);
        _book.Alpha = 1f - Math.Max(0f, mix * 2f - 1f);
    }

    // Puts one frame of the opening animation (index Open.Length is the finished book) at its native spot, moved
    // `shift` px sideways.
    private static void PlaceBookFrame(ObjectRect rect, ref int shown, int index, int shift) {
        var isFinal = index >= BookFrameData.Open.Length;
        var f = isFinal ? new BookFrameData.Frame(0, 0, BookFrameData.BookWidth, BookFrameData.BookHeight) : BookFrameData.Open[index];

        if (shown != index) {
            shown = index;
            rect.ChangeTexture(TextureHelper.FromUiAtlas(isFinal ? "BookGems/Book" : $"BookGems/Open/{index + 1}", 0, false));
            rect.Resize(Sz(f.W), Sz(f.H));
        }

        rect.X = Px(f.X) + shift;
        rect.Y = Py(f.Y);
    }

    private void ShowStaticBook() {
        if (_shownOpenFrame == -2) {
            return;
        }
        _shownOpenFrame = -2;
        _bookBlend.Visible = false;
        _book.Alpha = 1f;
        _book.ChangeTexture(TextureHelper.FromUiAtlas("BookGems/Book", 0, false));
        _book.X = Px(0);
        _book.Y = Py(0);
        _book.Resize(Sz(BookFrameData.BookWidth), Sz(BookFrameData.BookHeight));
    }

    #endregion

    #region Page content

    private void RebuildPages() {
        BuildProfilePage(_pages[(int) BookPage.Profile]);
        BuildCharactersPage(_pages[(int) BookPage.Characters]);
        BuildIconMessagePage(_pages[(int) BookPage.Graveyard], "GRAVEYARD", "Graveyard", GraveyardEmpty);
        RebuildRewardPages();
    }

    // The account name sits halfway between the two rules (under PROFILE at Sz(46), under the name at Sz(92)). The text control
    // centres its whole line box, which includes the empty descender space below the letters, so the visible capitals come out
    // ~3px lower than the box centre - hence the nudge up.
    private static readonly int NameCenterY = PageTop + (Sz(46) + Sz(92)) / 2 - 3;

    private void BuildProfilePage(Container page) {
        page.RemoveChildren();

        // Left page: who you are.
        page.AddChild(Text("PROFILE", FontGroup.MyriadPro, TitleSize, LeftPageCenterX, PageTop + Sz(16), UiAnchor.Middle));
        page.AddChild(Rule(LeftPageCenterX, PageTop + Sz(46), LeftPageW - Sz(40)));
        if (_accountName.Length > 0) {
            page.AddChild(Text(_accountName, FontGroup.MyriadPro, 42f, LeftPageCenterX, NameCenterY, UiAnchor.Middle, maxWidth: LeftPageW - 10));
        }
        page.AddChild(Rule(LeftPageCenterX, PageTop + Sz(92), LeftPageW - Sz(40)));

        // Gold on top of fame, flush left (the same left edge as the stat rows below), which leaves the right side of this
        // block free for more visual content later; then the account's lifetime numbers run down the rest of the page.
        const int currencyRowGap = 38;
        var currencyLeft = LeftPageX + Sz(14);
        var goldY = PageTop + Sz(114);
        page.AddChild(CurrencyRow("Console/GoldCoin0", _gold.ToString("N0"), currencyLeft, goldY, leftAligned: true));
        page.AddChild(CurrencyRow("Console/CopperCoin0", _fame.ToString("N0"), currencyLeft, goldY + currencyRowGap, leftAligned: true));
        var currencyRuleY = goldY + currencyRowGap + 26;
        page.AddChild(Rule(LeftPageCenterX, currencyRuleY, LeftPageW - Sz(40)));
        BuildAccountStats(page, currencyRuleY + 26);

        // Right page: the character you last played (see LastPlayedCharacter).
        page.AddChild(Text("LAST PLAYED", FontGroup.MyriadPro, TitleSize, RightPageCenterX, PageTop + Sz(16), UiAnchor.Middle));
        page.AddChild(Rule(RightPageCenterX, PageTop + Sz(46), RightPageW - Sz(40)));

        var champion = LastPlayedCharacter();
        if (champion == null) {
            page.AddChild(Text("No characters yet.", FontGroup.MyriadPro, BodySize, RightPageCenterX, PageTop + Sz(120), UiAnchor.Middle));
            page.AddChild(Text("Open the Characters tab", FontGroup.MyriadPro, SmallSize + 2, RightPageCenterX, PageTop + Sz(150), UiAnchor.Middle));
            page.AddChild(Text("to forge your first character.", FontGroup.MyriadPro, SmallSize + 2, RightPageCenterX, PageTop + Sz(172), UiAnchor.Middle));
            return;
        }

        BuildCharacterSummary(page, champion, includeFame: true);
    }

    // The right-hand readout shared by "Last Played" and "Details": portrait, class, level + experience, (fame for the
    // Last Played character only), all eight stats in two columns, and a PLAY button that launches THIS character.
    private void BuildCharacterSummary(Container page, Character character, bool includeFame) {
        var props = ObjectLibrary.TypeToObjectProps[character.ObjectType];
        var cx = RightPageCenterX;

        page.AddChild(Portrait(character, cx, PageTop + 128, 112));
        page.AddChild(Text(props.ObjectId.ToUpperInvariant(), FontGroup.MyriadPro, 30f, cx, PageTop + 208, UiAnchor.Middle));
        page.AddChild(Text($"LEVEL {character.Level}", CharacterFont, 20f, cx, PageTop + 246, UiAnchor.Middle, color: InkSoft, outline: 1));

        if (includeFame) {
            page.AddChild(CurrencyRow("Console/CopperCoin0", character.CurrentFame.ToString("N0"), cx, PageTop + 284));
        }

        (string Label, int Value)[] stats = [
            ("HP", character.MaxHitPoints), ("MP", character.MaxMagicPoints),
            ("ATT", character.Attack), ("DEF", character.Defense),
            ("SPD", character.Speed), ("DEX", character.Dexterity),
            ("VIT", character.Vitality), ("WIS", character.Wisdom)
        ];
        var top = PageTop + (includeFame ? 330 : 304);
        var step = includeFame ? 32 : 34;
        for (var i = 0; i < stats.Length; i++) {
            page.AddChild(StatLine(stats[i].Label, stats[i].Value.ToString(), cx - 160 + (i % 2) * 170, top + (i / 2) * step));
        }

        page.AddChild(BuildScrollButton("PLAY", cx, PageBottom - PlayButtonBottomGap - PlayButtonHeight / 2, PlayButtonWidth, PlayButtonHeight, () => _onPlay(character)));
    }

    private void BuildCharactersPage(Container page) {
        page.RemoveChildren();

        // Left page: the roster grid, plus a "new character" tile that opens the creation popup.
        page.AddChild(Text("CHARACTERS", FontGroup.MyriadPro, TitleSize, LeftPageCenterX, PageTop + Sz(16), UiAnchor.Middle));

        const int cols = 3;
        const int tile = 122;
        const int gap = 10;
        var gridW = cols * tile + (cols - 1) * gap;
        var gridLeft = LeftPageCenterX - gridW / 2;
        var gridTop = PageTop + Sz(40);

        const int maxTiles = 9;
        var shown = Math.Min(_characters.Count, maxTiles - 1);
        for (var i = 0; i < shown; i++) {
            page.AddChild(BuildCharacterTile(_characters[i], i, gridLeft + (i % cols) * (tile + gap), gridTop + (i / cols) * (tile + gap), tile));
        }
        var newIndex = shown;
        page.AddChild(BuildNewCharacterTile(gridLeft + (newIndex % cols) * (tile + gap), gridTop + (newIndex / cols) * (tile + gap), tile));

        // Right page: the selected character.
        var character = CurrentCharacter;
        page.AddChild(Text("DETAILS", FontGroup.MyriadPro, TitleSize, RightPageCenterX, PageTop + Sz(16), UiAnchor.Middle));
        page.AddChild(Rule(RightPageCenterX, PageTop + Sz(46), RightPageW - Sz(40)));

        if (character == null) {
            page.AddChild(Text("No characters yet.", FontGroup.MyriadPro, BodySize, RightPageCenterX, PageTop + Sz(120), UiAnchor.Middle));
            page.AddChild(BuildTextButton("FORGE A CHARACTER", FontGroup.MyriadPro, 26f, RightPageCenterX, PageTop + Sz(170), UiAnchor.Middle, () => _onForge()));
            return;
        }

        // No fame here: fame belongs to the Last Played (alive) character readout.
        BuildCharacterSummary(page, character, includeFame: false);
    }

    // Left page only (icon + one line) - the right page is deliberately left empty for now.
    private void BuildIconMessagePage(Container page, string title, string iconName, string leftLine) {
        page.RemoveChildren();

        page.AddChild(Text(title, FontGroup.MyriadPro, TitleSize, LeftPageCenterX, PageTop + Sz(16), UiAnchor.Middle));
        page.AddChild(new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas($"BookGems/Icon/{iconName}Big", 0, false),
            X = LeftPageCenterX,
            Y = PageTop + Sz(120),
            Width = 112,
            Height = 112,
            Anchor = UiAnchor.Middle,
            OutlineEnabled = false,
            GlowEnabled = false
        }));
        page.AddChild(Text(leftLine, FontGroup.MyriadPro, BodySize, LeftPageCenterX, PageTop + Sz(200), UiAnchor.Middle, maxWidth: LeftPageW - 10));
    }

    // Account-wide numbers for the Profile page: the account's lifetime totals, the best any one character has
    // done (the account server's records, or a live character that has already beaten them), and each class's
    // best level / fame. Rows stop at the bottom of the page, so a longer class roster just gets cut off
    // rather than running off the book.
    private void BuildAccountStats(Container page, int top) {
        var stats = _account?.Stats;
        if (stats == null) {
            return;
        }

        var left = LeftPageX + Sz(14);
        var right = LeftPageX + LeftPageW - Sz(14);
        var rowH = Sz(17);
        var limit = PageBottom - Sz(8);
        var y = top;

        var bestLevel = 0;
        var bestFame = stats.BestCharacterFame;
        foreach (var c in _characters) {
            bestLevel = Math.Max(bestLevel, c.Level);
            bestFame = Math.Max(bestFame, c.CurrentFame);
        }
        foreach (var classStat in stats.ClassStats) {
            bestLevel = Math.Max(bestLevel, classStat.BestLevel);
        }

        var guild = string.IsNullOrEmpty(_account.GuildName) ? "NONE" : _account.GuildName.ToUpperInvariant();
        (string Label, string Value)[] rows = [
            ("CHARACTERS", _characters.Count.ToString("N0")),
            ("HIGHEST LEVEL REACHED", bestLevel.ToString("N0")),
            ("HIGHEST FAME REACHED", bestFame.ToString("N0")),
            ("LIFETIME FAME EARNINGS", (stats.TotalFame + _lifetimeFameEarned).ToString("N0")),
            ("LIFETIME GOLD EARNINGS", (stats.TotalCredits + _lifetimeGoldEarned).ToString("N0")),
            ("GUILD", guild)
        ];
        foreach (var (label, value) in rows) {
            page.AddChild(AccountStatLine(label, value, left, right, y));
            y += rowH;
        }

        if (stats.ClassStats.Length == 0) {
            return;
        }

        // Then a divider and each class's best level / fame.
        y += Sz(6);
        page.AddChild(Rule(LeftPageCenterX, y, LeftPageW - Sz(40)));
        y += Sz(14);

        foreach (var classStat in stats.ClassStats) {
            if (y > limit || !ObjectLibrary.TypeToObjectProps.TryGetValue((ushort) classStat.ObjectType, out var props)) {
                continue;
            }
            page.AddChild(AccountStatLine(props.ObjectId.ToUpperInvariant(), $"LV {classStat.BestLevel}   {classStat.BestFame:N0} FAME", left, right, y));
            y += rowH;
        }
    }

    // The character last launched into the game (Settings.LastPlayedCharacterId, saved on PLAY); if that one is
    // gone or nothing has been played yet, the highest-fame character stands in.
    private Character LastPlayedCharacter() {
        Character best = null;
        foreach (var c in _characters) {
            if (c.Id == (int) Settings.LastPlayedCharacterId) {
                return c;
            }
            if (best == null || c.CurrentFame > best.CurrentFame) {
                best = c;
            }
        }
        return best;
    }

    private Sprite BuildCharacterTile(Character character, int index, int x, int y, int size) {
        var tile = new Container { X = x, Y = y };
        tile.MouseEnabled = true;

        var selected = index == _selectedIndex;
        tile.AddChild(new ColorRect(new ColorRectConfig { Width = size, Height = size, Color = Ink, Alpha = selected ? 0.95f : 0.55f }));
        tile.AddChild(new ColorRect(new ColorRectConfig { Width = size - 4, Height = size - 4, Color = selected ? TileSelected : TileIdle, Alpha = selected ? 0.75f : 0.28f }) { X = 2, Y = 2 });

        var props = ObjectLibrary.TypeToObjectProps[character.ObjectType];
        // Drawn larger than the 32x32 cell suggests because the art only fills about half of its cell; centred in the space above the name.
        tile.AddChild(Portrait(character, size / 2, size / 2 - 19, 88));
        tile.AddChild(Text(props.ObjectId.ToUpperInvariant(), CharacterFont, 16f, size / 2, size - 32, UiAnchor.Middle, maxWidth: size - 8, outline: 1));
        tile.AddChild(Text($"LV {character.Level}", CharacterFont, 14f, size / 2, size - 14, UiAnchor.Middle, color: InkSoft, outline: 1));

        var down = false;
        tile.AddEventListener(MouseEvent.LeftDown, () => down = true);
        tile.AddEventListener(MouseEvent.LeftUp, () => {
            if (down && !_flipping && _entranceComplete) {
                _selectedIndex = index;
                BuildCharactersPage(_pages[(int) BookPage.Characters]);
            }
            down = false;
        });
        return tile;
    }

    private Sprite BuildNewCharacterTile(int x, int y, int size) {
        var tile = new Container { X = x, Y = y };
        tile.MouseEnabled = true;

        tile.AddChild(new ColorRect(new ColorRectConfig { Width = size, Height = size, Color = Ink, Alpha = 0.4f }));
        tile.AddChild(new ColorRect(new ColorRectConfig { Width = size - 4, Height = size - 4, Color = TileIdle, Alpha = 0.10f }) { X = 2, Y = 2 });
        var plus = Text("+", FontGroup.MyriadPro, 48f, size / 2, size / 2 - 12, UiAnchor.Middle, color: InkSoft);
        var label = Text("NEW", CharacterFont, 16f, size / 2, size - 32, UiAnchor.Middle, color: InkSoft, outline: 1);
        tile.AddChild(plus);
        tile.AddChild(label);

        var down = false;
        tile.AddEventListener(MouseEvent.MouseOver, () => { plus.SetColor(Hover); label.SetColor(Hover); });
        tile.AddEventListener(MouseEvent.MouseOut, () => { plus.SetColor(InkSoft); label.SetColor(InkSoft); });
        tile.AddEventListener(MouseEvent.LeftDown, () => down = true);
        tile.AddEventListener(MouseEvent.LeftUp, () => {
            if (down && !_flipping && _entranceComplete) {
                _onForge();
            }
            down = false;
        });
        return tile;
    }

    #endregion

    #region Small builders

    private static SimpleText Text(string text, FontGroup font, float size, int x, int y, UiAnchor anchor, uint color = Ink, int maxWidth = 0, int outline = 2) {
        var cfg = new TextConfig {
            Text = text,
            FontSize = size,
            FontType = FontType.Bold,
            FontGroup = font,
            Color = color,
            OutlineColor = color,
            OutlineThickness = outline,
            X = x,
            Y = y,
            Anchor = anchor
        };
        if (maxWidth > 0) {
            cfg.MaxWidth = maxWidth;
        }
        return new SimpleText(cfg);
    }

    private static ColorRect Rule(int centerX, int y, int width) =>
        new(new ColorRectConfig { Width = width, Height = 2, Color = InkSoft, Alpha = 0.6f }) { X = centerX - width / 2, Y = y };

    // Centred icon + number, e.g. the gold and fame readouts.
    private static Container CurrencyRow(string iconLookup, string amount, int centerX, int centerY, bool leftAligned = false) {
        const int icon = 26;
        const int gap = 8;
        var row = new Container();
        var text = Text(amount, FontGroup.MyriadPro, BodySize + 4, 0, centerY, UiAnchor.MiddleLeft);
        var total = icon + gap + text.Width;
        var left = leftAligned ? centerX : centerX - total / 2;     // leftAligned: the x given is the row's left edge
        row.AddChild(new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas(iconLookup, 0, false),
            X = left + icon / 2,
            Y = centerY,
            Width = icon,
            Height = icon,
            Anchor = UiAnchor.Middle,
            OutlineEnabled = false,
            GlowEnabled = false
        }));
        text.X = left + icon + gap;
        row.AddChild(text);
        return row;
    }

    private static Container StatLine(string label, string value, int left, int centerY) {
        var row = new Container();
        row.AddChild(Text(label, CharacterFont, 20f, left, centerY, UiAnchor.MiddleLeft, color: InkSoft, outline: 1));
        row.AddChild(Text(value, CharacterFont, 22f, left + 64, centerY, UiAnchor.MiddleLeft, outline: 1));
        return row;
    }

    // A label on the left and its value pushed to the right edge, e.g. the Profile page's account stats.
    private static Container AccountStatLine(string label, string value, int left, int right, int centerY) {
        var row = new Container();
        row.AddChild(Text(label, CharacterFont, 16f, left, centerY, UiAnchor.MiddleLeft, color: InkSoft, outline: 1));
        row.AddChild(Text(value, CharacterFont, 20f, right, centerY, UiAnchor.MiddleRight, outline: 1));
        return row;
    }

    private static ObjectRect Portrait(Character character, int centerX, int centerY, int size) {
        var textureData = ObjectLibrary.TypeToTextureData[character.ObjectType];
        return new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.Create(textureData.AnimatedTextures.FaceDown[0], TextureType.GameAtlas),
            X = centerX,
            Y = centerY,
            Width = size,
            Height = size,
            Anchor = UiAnchor.Middle,
            OutlineEnabled = false,
            GlowEnabled = false
        });
    }

    // The back icon: a Container wrapping the icon sprite that grows a little on hover (a tint wouldn't read on the near-black art).
    private static Container BuildBackIconButton(int centerX, int centerY, Action onClicked) {
        var button = new Container { X = centerX, Y = centerY };
        button.SetAnchor(UiAnchor.Middle);
        button.MouseEnabled = true;

        button.AddChild(new ObjectRect(new ObjectRectConfig {
            Texture = TextureHelper.FromUiAtlas("Icons/BookBackIcon", 0, false),
            Width = BackIconWidth,
            Height = BackIconHeight,
            OutlineEnabled = false,
            GlowEnabled = false
        }));

        var down = false;
        button.AddEventListener(MouseEvent.MouseOver, () => button.Scale = new Vector2(BackIconHoverScale));
        button.AddEventListener(MouseEvent.MouseOut, () => button.Scale = Vector2.One);
        button.AddEventListener(MouseEvent.LeftDown, () => down = true);
        button.AddEventListener(MouseEvent.LeftUp, () => {
            if (down) {
                onClicked();
            }
            down = false;
        });
        return button;
    }

    // A parchment scroll with a label in the book's ink; it darkens a little while the mouse is over it, and the whole scroll is the
    // click target. Centred on (centerX, centerY).
    private static Container BuildScrollButton(string text, int centerX, int centerY, int width, int height, Action onClicked) {
        var button = new Container { X = centerX - width / 2, Y = centerY - height / 2 };
        button.MouseEnabled = true;

        var scroll = new NineSliceRect(new NineSliceConfig {
            SliceData = SliceLibrary.DarkAgesParchment,
            CutX = 12,
            CutY = 12,
            Width = width,
            Height = height
        });
        button.AddChild(scroll);
        button.AddChild(Text(text, FontGroup.MyriadPro, 26f, width / 2, height / 2, UiAnchor.Middle, outline: 1));

        var down = false;
        button.AddEventListener(MouseEvent.MouseOver, () => scroll.ColorTransformation = ScrollHoverTint);
        button.AddEventListener(MouseEvent.MouseOut, () => scroll.ColorTransformation = new ColorTransform(1f, 1f, 1f, 1f));
        button.AddEventListener(MouseEvent.LeftDown, () => down = true);
        button.AddEventListener(MouseEvent.LeftUp, () => {
            if (down) {
                onClicked();
            }
            down = false;
        });
        return button;
    }

    // Plain text that darkens to the hover colour; the whole text area is the click target.
    private static Container BuildTextButton(string text, FontGroup font, float size, int x, int y, UiAnchor anchor, Action onClicked) {
        var button = new Container { X = x, Y = y };
        button.SetAnchor(anchor);
        button.MouseEnabled = true;

        var label = Text(text, font, size, 0, 0, UiAnchor.LeftTop);
        button.AddChild(label);

        var down = false;
        button.AddEventListener(MouseEvent.MouseOver, () => label.SetColor(Hover));
        button.AddEventListener(MouseEvent.MouseOut, () => label.SetColor(Ink));
        button.AddEventListener(MouseEvent.LeftDown, () => down = true);
        button.AddEventListener(MouseEvent.LeftUp, () => {
            if (down) {
                onClicked();
            }
            down = false;
        });
        return button;
    }

    #endregion
}
