<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <LangVersion>Latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <PlatformTarget></PlatformTarget>
        <OutputPath>../bin/debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <PlatformTarget>x64</PlatformTarget>
        <OutputPath>../bin/release</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Common.Protocol\Common.Protocol.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="Ionic.Zlib.Core" Version="1.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
        <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
        <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Resources\Config\Data\appEngineConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Database\Schema.sql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\postgresConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\redisConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\rpcServerConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\rpcClientConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\realmConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\gameServerConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\newAccountsConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\newCharsConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\newsConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\musicConfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\News\PatchNotes.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Guild0.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Guild1.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Guild2.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Guild3.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Nexus.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Vault.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Realm.jm">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Xml\Merchants\NexusMerchants.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Config\GuildHall.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Config\Nexus.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Config\Vault.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\World\Data\Config\Realm.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Config\Data\gameConfig.xml">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Projectiles\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Containers.xml">
        <Link>Resources\Xml\Data\Xmls\Containers.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Equip.xml">
        <Link>Resources\Xml\Data\Xmls\Equip.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Ground.xml">
        <Link>Resources\Xml\Data\Xmls\Ground.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\NPCs.xml">
        <Link>Resources\Xml\Data\Xmls\NPCs.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Objects.xml">
        <Link>Resources\Xml\Data\Xmls\Objects.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Players.xml">
        <Link>Resources\Xml\Data\Xmls\Players.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Projectiles.xml">
        <Link>Resources\Xml\Data\Xmls\Projectiles.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\Shore.xml">
        <Link>Resources\Xml\Data\Xmls\Shore.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\WaW-Client\WaWClient\Content\Xmls\StaticObjects.xml">
        <Link>Resources\Xml\Data\Xmls\StaticObjects.xml</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
