// <auto-generated/>

using WaW.Common.SourceGen;

namespace WaWClient.Rendering;

partial class Render
{
    private static partial ShaderSource GroundShaderSource => new ShaderSource("Ground", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform mat4 FullMatrix;
uniform float GameTime;

layout(location = 0) in vec2 iLocalPos;
layout(location = 1) in vec2 iLocalUV;
layout(location = 2) in vec4 iPosition;
layout(location = 3) in vec4 iUV;
layout(location = 4) in vec4 iAnimate;
layout(location = 5) in vec4 iMask;
layout(location = 6) in vec4 iTemp;

out vec2 GROUND_OUTPUT_baseUV;
out vec2 GROUND_OUTPUT_coreUV;
out vec4 GROUND_OUTPUT_UV;
out vec4 GROUND_OUTPUT_Mask;
out float GROUND_OUTPUT_Swizzle;

void main() {
    vec4 inputPosition = vec4(iLocalPos, 0, 1);
    inputPosition.xy = (inputPosition.xy - 0.5) * 1.002 + 0.5;
    inputPosition.xy += iPosition.xy;
    gl_Position = inputPosition * FullMatrix;

    GROUND_OUTPUT_baseUV = iLocalUV;
    GROUND_OUTPUT_coreUV.x = iLocalUV.x + iPosition.z + sin(GameTime * iAnimate.x) + GameTime * iAnimate.z;
    GROUND_OUTPUT_coreUV.y = iLocalUV.y + iPosition.w + sin(GameTime * iAnimate.y) + GameTime * iAnimate.w;
    GROUND_OUTPUT_UV = iUV;
    GROUND_OUTPUT_Mask = iMask;
    GROUND_OUTPUT_Swizzle = iTemp.x;
}

""", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform sampler2D GameTexture;
uniform vec4 AlphaBlends[8];

in vec2 GROUND_OUTPUT_baseUV;
in vec2 GROUND_OUTPUT_coreUV;
in vec4 GROUND_OUTPUT_UV;
in vec4 GROUND_OUTPUT_Mask;
in float GROUND_OUTPUT_Swizzle;

out vec4 FragColor;

void main() {
    vec2 tileTexelSize = round(GROUND_OUTPUT_UV.zw * 4096.0);
    vec2 tileTexelOrigin = round(GROUND_OUTPUT_UV.xy * 4096.0);
    vec2 wrappedTexels = floor(fract(GROUND_OUTPUT_coreUV) * tileTexelSize);
    vec2 uv = (tileTexelOrigin + wrappedTexels + 0.5) / 4096.0;
    uv = mix(uv.xy, uv.yx, GROUND_OUTPUT_Swizzle);

    vec4 ogColor = texture(GameTexture, uv);

    if (GROUND_OUTPUT_Mask.x > -1.0) {
        vec2 maskTexelSize = round(GROUND_OUTPUT_Mask.zw * 4096.0);
        vec2 maskTexelOrigin = round(GROUND_OUTPUT_Mask.xy * 4096.0);
        vec2 maskTexels = floor(GROUND_OUTPUT_baseUV * maskTexelSize);
        float alpha = texture(GameTexture, (maskTexelOrigin + maskTexels + 0.5) / 4096.0).a;
        ogColor.a = alpha;
    }

    FragColor = ogColor;
}

""");
    private static partial ShaderSource ShadowShaderSource => new ShaderSource("Shadow", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

#define ShadowBuffer 

uniform mat4 FullMatrix;
uniform mat4 BillMatrix;

const vec2 shadowPos[6] = vec2[6](
    vec2(-0.5, 0.25),
    vec2(0.5, 0.25),
    vec2(-0.5, -0.25),
    vec2(-0.5, -0.25),
    vec2(0.5, 0.25),
    vec2(0.5, -0.25)
);

const vec2 shadowUV[6] = vec2[6](
    vec2(0.0, 1.0),
    vec2(1.0, 1.0),
    vec2(0.0, 0.0),
    vec2(0.0, 0.0),
    vec2(1.0, 1.0),
    vec2(1.0, 0.0)
);

struct InstanceData {
    vec2 Position;
    float Scale;
    uint Color;
};




uniform highp usampler2D SsboTex0;   // instance data: STRIDE texels (uvec4) per instance, 2048 texels per row

uvec4 fetchTexel(int index) { return texelFetch(SsboTex0, ivec2(index % 2048, index / 2048), 0); }

InstanceData fetchInstance(int id) {
    uvec4 t = fetchTexel(id);
    InstanceData d;
    d.Position = uintBitsToFloat(t.xy);
    d.Scale = uintBitsToFloat(t.z);
    d.Color = t.w;
    return d;
}

out vec2 BaseUV;
flat out uint Color;

void main() {
    int instanceId = gl_VertexID / 6;
    int verId = gl_VertexID % 6;
    
    InstanceData data = fetchInstance(instanceId);
    
    vec4 pos = vec4(shadowPos[verId] * data.Scale, 0, 1) * BillMatrix;
    pos.xy += data.Position.xy;
    
    gl_Position = pos * FullMatrix;
    
    BaseUV = shadowUV[verId];
    Color = data.Color;
}
""", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

out vec4 FragColor;

in vec2 BaseUV;
flat in uint Color;

// ABGR
vec3 unpackColor(uint color) {
    return vec3(
        float(color & 0x0000FFu) / 255.0,
        float((color & 0x00FF00u) >> 8u) / 255.0,
        float((color & 0xFF0000u) >> 16u) / 255.0
    );
}

void main() {
    float dx = 0.5 - BaseUV.x, dy = 0.5 - BaseUV.y;
    float dist = dx * dx + dy * dy;
    float distFromCenter = 0.25 - dist;
    
    FragColor = vec4(unpackColor(Color), distFromCenter * 1.5);
}


""");
    private static partial ShaderSource ModelShaderSource => new ShaderSource("Model", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform mat4 FullMatrix;
// The camera's depth column (M12, M22, M32, M42 of the camera matrix, as the CPU's DepthMatrix): screen y of a ground point =
// x * M12 + y * M22 + M42. Used for baked static props (see below). FullMatrix is uploaded transposed, so it is NOT re-derived from it.
uniform vec4 DepthColumn;

layout (location = 0) in vec3 Position;
layout (location = 1) in vec2 BaseUV;
layout (location = 2) in vec3 iPosition;
layout (location = 3) in vec4 iUV;
layout (location = 4) in vec3 iExtra;

out vec2 MODEL_OUT_BaseUV;
out vec4 MODEL_OUT_UV;
out vec3 MODEL_OUT_Extra;
out float MODEL_OUT_Zed;

void main() {
    float s = sin(iExtra.x);
    float c = cos(iExtra.x);

    vec4 pos = vec4(Position.xy * mat2(c, -s, s, c), Position.z, 1);
    pos = vec4((pos.xy - 0.5) * 1.005 + 0.5, pos.zw);
    pos.xyz += iPosition;

    MODEL_OUT_BaseUV = BaseUV;
    MODEL_OUT_UV = iUV;
    MODEL_OUT_Extra = iExtra;
    MODEL_OUT_Zed = pos.z;

    pos = pos * FullMatrix;

    // Depth. A number >= 0 is the depth itself (worked out on the CPU from the camera, every frame). Static props baked once into a
    // per-area mesh (StaticProps.cs, 2026-09-22) cannot know the camera, so they carry a code instead and the depth is computed here with
    // the same formula Entity.UpdateVisibility uses: 0.5 + 0.4 x the screen y of the ground point + a tiny per-object nudge.
    //   -10 + nudge x 1000: the ground point is iPosition.xy (props, card corners)
    //   -20 + nudge x 1000: the ground point is iPosition.xy + 0.5 (walls and wall tops, stored at their tile corner)
    float depth = iExtra.y;
    if (depth < -5.0) {
        float center = depth < -15.0 ? -20.0 : -10.0;
        vec2 ground = iPosition.xy + (depth < -15.0 ? vec2(0.5, 0.5) : vec2(0.0, 0.0));
        depth = 0.5 + 0.4 * (ground.x * DepthColumn.x + ground.y * DepthColumn.y + DepthColumn.w) + (depth - center) * 0.001;
    }
    pos.z = depth;

    gl_Position = pos;
}

""", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform sampler2D GameTexture;

in vec2 MODEL_OUT_BaseUV;
in vec4 MODEL_OUT_UV;
in vec3 MODEL_OUT_Extra;
in float MODEL_OUT_Zed;

out vec4 FragColor;

vec2 map(vec2 base, vec2 uvMin, vec2 uvMax) {
    return vec2(base.x * (uvMax.x - uvMin.x) + uvMin.x, base.y * (uvMax.y - uvMin.y) + uvMin.y);
}

void main() {
    vec2 uv = map(MODEL_OUT_BaseUV, MODEL_OUT_UV.xy, MODEL_OUT_UV.xy + MODEL_OUT_UV.zw);
    vec4 color = texture(GameTexture, uv);

    // The props' pictures have see-through parts (the pixel art's background): cut them out instead of dividing by an alpha of 0.
    if (color.a < 0.5) {
        discard;
    }

    color /= color.a;
    color.rgb -= MODEL_OUT_Extra.z * 0.241 * clamp(0.6 - MODEL_OUT_Zed, 0.0 , 0.6);
    
    FragColor = color;
}
""");
    private static partial ShaderSource ObjectShaderSource => new ShaderSource("Object", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform mat4 FullMatrix;
uniform mat4 BillMatrix;
uniform int RenderPass;

const int OpaquePass = 0;
const int OutlineGlowPass = 1;

layout(location = 0) in vec2 iLocalPos;
layout(location = 1) in vec2 iLocalUV;
layout(location = 2) in vec4 iPosition;
layout(location = 3) in vec4 iUV;
layout(location = 4) in vec4 iScale;
layout(location = 5) in vec4 iRotation;
layout(location = 6) in vec4 iExtra;
layout(location = 7) in vec4 iColor;
layout(location = 8) in vec4 iMask1;
layout(location = 9) in vec4 iMask2;

// Extra used to be a struct-typed varying in the middle of this interface block. Some
// GLSL compilers/drivers mishandle struct members inside in/out interface blocks and
// corrupt the plain vec2/vec4 varyings around them - on this GPU/driver it was zeroing
// out the per-pixel variation of BaseUV/UV (declared before it), making every sprite
// sample a single texel instead of its real texture. Flattened to a plain vec4 here.
out vec2 OBJECT_OUT_BaseUV;
out vec4 OBJECT_OUT_UV;
out vec4 OBJECT_OUT_Extra;
out vec4 OBJECT_OUT_Color;
out vec4 OBJECT_OUT_Mask1;
out vec4 OBJECT_OUT_Mask2;

const float TypeGameObject = 0.0;
const float TypeText = 3.0;
const float TypeBar = 4.0;
const float TypeEffect = 5.0;

vec2 GetUV(vec2 uv, float flip) {
    uv.x = 0.5 + (0.5 - uv.x) * flip;
    return uv;
}

void main() {
    float extraType = iExtra.x;
    float extraSortId = iExtra.y;

    if (RenderPass == OutlineGlowPass && extraType != TypeGameObject){
        // Discard vertex: push it well past the far clip plane with a normal, non-degenerate
        // w=1 (the old vec4(2,0,0,0) had w=0, a degenerate/infinite clip coordinate that some
        // older GPU drivers clip incorrectly instead of cleanly discarding).
        gl_Position = vec4(0, 0, 2, 1);
        return;
    }

    vec4 position = vec4(iLocalPos, 0, 1);
    position.xy *= iScale.xy;

    mat4 rotate = mat4(
        iRotation.y * iRotation.z, iRotation.x * iRotation.z, 0, iScale.z * iRotation.z * -iRotation.w,
        -iRotation.x * iRotation.z, iRotation.y * iRotation.z, 0, iScale.w * iRotation.z,
        0, 0, 1, 0,
        0, 0, 0, 1
    );

    position = position * rotate * BillMatrix;
    position.xyz += iPosition.xyz;
    position = position * FullMatrix;
    position.z = extraSortId;
    gl_Position = position;

    OBJECT_OUT_BaseUV = GetUV(iLocalUV, iRotation.w);
    OBJECT_OUT_UV = iUV;
    OBJECT_OUT_Extra = iExtra;
    OBJECT_OUT_Color = iColor;
    OBJECT_OUT_Mask1 = iMask1;
    OBJECT_OUT_Mask2 = iMask2;
}

""", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;
precision highp float;

// Extra used to be a struct-typed varying in the middle of this interface block. Some
// GLSL compilers/drivers mishandle struct members inside in/out interface blocks and
// corrupt the plain vec2/vec4 varyings around them - on this GPU/driver it was zeroing
// out the per-pixel variation of BaseUV/UV (declared before it), making every sprite
// sample a single texel instead of its real texture. Flattened to a plain vec4 here:
// x=Type, y=SortId, z=Shade, w=Alpha.
in vec2 OBJECT_OUT_BaseUV;
in vec4 OBJECT_OUT_UV;
in vec4 OBJECT_OUT_Extra;
in vec4 OBJECT_OUT_Color;
in vec4 OBJECT_OUT_Mask1;
in vec4 OBJECT_OUT_Mask2;

out vec4 FragColor;

uniform sampler2D GameTexture;
uniform float PixelRange;
uniform vec2 TextTextureSize;
uniform sampler2D TextTexture;
uniform float Zoom;
uniform int RenderPass; // 0 = opaque, 1 = transparent

const int OpaquePass = 0;
const int OutlineGlowPass = 1;

const float TypeGameObject = 0.0;
const float TypeText = 3.0;
const float TypeBar = 4.0;
const float TypeEffect = 5.0;

vec2 map(vec2 base, vec2 uvMin, vec2 uvMax) {
    return vec2(base.x * (uvMax.x - uvMin.x) + uvMin.x, base.y * (uvMax.y - uvMin.y) + uvMin.y);
}

float median(float a, float b, float c) {
    return max(min(a, b), min(max(a, b), c));
}

vec4 GetGameObject() {
    // uvMax precomputed once, reused in map()
    vec2 uvMax = OBJECT_OUT_UV.xy + OBJECT_OUT_UV.zw;
    vec2 uv = map(OBJECT_OUT_BaseUV, OBJECT_OUT_UV.xy, uvMax);
    // textureLod at LOD 0 instead of textureGrad() with manually computed dFdx/dFdy: those
    // derivatives are unreliable on this GPU/driver (garbage/degenerate mip selection made
    // sprites look like flat blocks of solid color). Plain texture() (automatic derivatives)
    // isn't safe either here - screen-space UV derivatives are discontinuous at atlas sprite
    // boundaries, so automatic mip selection bleeds in neighboring atlas entries. Locking to
    // LOD 0 sidesteps derivatives entirely and always samples the sharp, correct texels.
    vec4 color = textureLod(GameTexture, uv, 0.0);
    color.rgb -= OBJECT_OUT_Extra.z * 0.241 * clamp(OBJECT_OUT_BaseUV.y - 0.4, 0.0, 0.4);
    if (RenderPass == OpaquePass){
        if (color.a < 1.0 || OBJECT_OUT_Extra.w < 1.0){
            discard;
        }
        return color;
    }

    // Fading-in objects (Extra.w = Alpha < 1) still show their full opaque texture color
    // here. The neighbor-sampling outline/glow effect that used to follow is disabled: on
    // this GPU/driver it misfired broadly instead of only along sprite edges, painting
    // whole quads with OBJECT_OUT_Color (opaque black for most objects) and blacking out
    // everything behind them. Purely cosmetic effect - safe to skip.
    if (color.a >= 1.0 && OBJECT_OUT_Extra.w < 1.0){
        return color;
    }

    discard;
}

vec4 GetText() {
    vec2 uv = map(OBJECT_OUT_BaseUV, OBJECT_OUT_UV.xy, OBJECT_OUT_UV.xy + OBJECT_OUT_UV.zw);
    vec3 samp = texture(TextTexture, uv).rgb;
    float pRange = PixelRange;
    vec2 dim = TextTextureSize;

    vec2 msdfUnit = pRange / dim;
    float sigDist = median(samp.r, samp.g, samp.b) - 0.5f;
    sigDist = sigDist * dot(msdfUnit, 0.5f / fwidth(uv));
    const float strokeThickness = 0.250f * 0.75f;
    float strokeDist = median(samp.r, samp.g, samp.b) - 0.25f * (1.0 + (pRange - 12.0) / pRange) - strokeThickness;
    strokeDist = -(abs(strokeDist) - strokeThickness);
    strokeDist = strokeDist * dot(msdfUnit, 0.5f / fwidth(uv));
    float opacity = clamp(sigDist + 0.5f, 0.0f, 1.0f);
    float strokeOpacity = clamp(strokeDist + 0.5f, 0.0f, 1.0f);
    return mix(vec4(0, 0, 0, 1), OBJECT_OUT_Color, opacity) * max(opacity, strokeOpacity);
}

void main() {
    vec4 outputColor;
    float id = OBJECT_OUT_Extra.x;

    if (id == TypeGameObject || id == TypeEffect) {
        outputColor = GetGameObject();
    } else if (id == TypeText) {
        outputColor = GetText();
    } else if (id == TypeBar) {
        outputColor = OBJECT_OUT_Color;
    } else {
        outputColor = vec4(0, 0, 0, 0);
    }

    outputColor.a *= OBJECT_OUT_Extra.w;
    if (outputColor.a == 0.0) {
        discard;
    }

    FragColor = outputColor;
}

""");
    private static partial ShaderSource ParticleShaderSource => new ShaderSource("Particle", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

uniform mat4 FullMatrix;
uniform mat4 BillMatrix;

const vec2 particlePos[6] = vec2[6](
    vec2(-0.1, 0.1),
    vec2(0.1, 0.1),
    vec2(-0.1, -0.1),
    vec2(-0.1, -0.1),
    vec2(0.1, 0.1),
    vec2(0.1, -0.1)
);

const vec2 particleUV[6] = vec2[6](
    vec2(0.0, 1.0),
    vec2(1.0, 1.0),
    vec2(0.0, 0.0),
    vec2(0.0, 0.0),
    vec2(1.0, 1.0),
    vec2(1.0, 0.0)
);

struct InstanceData {
    vec4 Position;
    vec4 Color;
};




uniform highp usampler2D SsboTex0;   // instance data: STRIDE texels (uvec4) per instance, 2048 texels per row

uvec4 fetchTexel(int index) { return texelFetch(SsboTex0, ivec2(index % 2048, index / 2048), 0); }

InstanceData fetchInstance(int id) {
    InstanceData d;
    d.Position = uintBitsToFloat(fetchTexel(id * 2));
    d.Color = uintBitsToFloat(fetchTexel(id * 2 + 1));
    return d;
}

out vec2 BaseUV;
out vec4 Color;
out float Depth;

void main() {
    int instanceId = gl_VertexID / 6;
    int verId = gl_VertexID % 6;
    
    InstanceData data = fetchInstance(instanceId);
    
    vec4 pos = vec4(particlePos[verId] * data.Position.w, 0, 1.0) * BillMatrix;
    
    
    BaseUV = particleUV[verId];
    Color = data.Color;
    
    vec4 depth = vec4(data.Position.xy, 0, 1) * FullMatrix;
    
    pos.xyz += data.Position.xyz;
    pos = pos * FullMatrix;
    pos.z = 0.5f + 0.4f * depth.y;
    
    gl_Position = pos;
}
""", """
#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp usampler2D;

out vec4 FragColor;

in vec2 BaseUV;
in vec4 Color;

const vec4 outline = vec4(0, 0, 0, 1);

void main() {
    float scale = 1.0;
    float ddx = abs(dFdx(BaseUV.x));
    float ddy = abs(dFdy(BaseUV.y));
    float dx = ddx * (0.1 / ddx);
    float dy = ddy * (0.1 / ddy);
    
    vec4 color = vec4(Color.xyz, 1);
    float val = float(BaseUV.x - dx <= 0.0 || BaseUV.y - dy <= 0.0 || BaseUV.x + dx >= 1.0 || BaseUV.y + dy >= 1.0);
    color = mix(color, outline, val);
    FragColor = color;
}
""");
}
