// <auto-generated/>
namespace System.Runtime.InteropServices.JavaScript
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    unsafe class __GeneratedInitializer
    {
        [global::System.ThreadStaticAttribute]
        static bool initialized;
        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute, global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods, "System.Runtime.InteropServices.JavaScript.__GeneratedInitializer", "WarriorsWeb")]
        static internal void __TrimmingPreserve_()
        {
        }

        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_LocalFolder_1310674786", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_PersistedFileList_1310674786", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_PersistNow_1344628367", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_WriteFile_805786592", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_Start_1568108894", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_Frame_296377270", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnResize_1367123461", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnFocus_1344628367", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnMouseMove_157530469", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnScroll_157530469", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnText_92020726", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnClipboard_92020726", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnMouseButton_2140725032", "WarriorsWeb.WebHost", "WarriorsWeb")]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute("__Wrapper_OnKey_571960800", "WarriorsWeb.WebHost", "WarriorsWeb")]
        static void __Register_()
        {
            if (initialized || global::System.Runtime.InteropServices.RuntimeInformation.OSArchitecture != global::System.Runtime.InteropServices.Architecture.Wasm)
                return;
            initialized = true;
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:LocalFolder", 1310674786, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:PersistedFileList", 1310674786, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:PersistNow", 1344628367, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Boolean]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:WriteFile", 805786592, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Array(global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Byte)]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:Start", 1568108894, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:Frame", 296377270, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Double]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnResize", 1367123461, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnFocus", 1344628367, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Boolean]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnMouseMove", 157530469, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Single, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Single]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnScroll", 157530469, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Single, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Single]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnText", 92020726, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnClipboard", 92020726, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnMouseButton", 2140725032, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Boolean, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Int32]);
            global::System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindManagedFunction("[WarriorsWeb]WarriorsWeb.WebHost:OnKey", 571960800, [global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Discard, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.Boolean, global::System.Runtime.InteropServices.JavaScript.JSMarshalerType.String]);
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_LocalFolder_1310674786(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer, __arguments_buffer + 1);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __invokeRetValUnmanaged__param)
            {
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
                string __invokeRetVal = default;
                try
                {
                    __invokeRetVal = global::WarriorsWeb.WebHost.LocalFolder();
                    // Marshal - Convert managed data to native data.
                    __invokeRetValUnmanaged.ToJS(__invokeRetVal);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_PersistedFileList_1310674786(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer, __arguments_buffer + 1);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __invokeRetValUnmanaged__param)
            {
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
                string __invokeRetVal = default;
                try
                {
                    __invokeRetVal = global::WarriorsWeb.WebHost.PersistedFileList();
                    // Marshal - Convert managed data to native data.
                    __invokeRetValUnmanaged.ToJS(__invokeRetVal);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_PersistNow_1344628367(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __saveSettings_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                bool saveSettings = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __saveSettings_native.ToManaged(out saveSettings);
                    global::WarriorsWeb.WebHost.PersistNow(saveSettings);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_WriteFile_805786592(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __path_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __data_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                string path = default;
                byte[] data = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __data_native.ToManaged(out data);
                    __path_native.ToManaged(out path);
                    global::WarriorsWeb.WebHost.WriteFile(path, data);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_Start_1568108894(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer, __arguments_buffer + 1);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __width_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __height_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __invokeRetValUnmanaged__param)
            {
                int width = default;
                int height = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
                int __invokeRetVal = default;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __height_native.ToManaged(out height);
                    __width_native.ToManaged(out width);
                    __invokeRetVal = global::WarriorsWeb.WebHost.Start(width, height);
                    // Marshal - Convert managed data to native data.
                    __invokeRetValUnmanaged.ToJS(__invokeRetVal);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_Frame_296377270(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __nowMs_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                double nowMs = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __nowMs_native.ToManaged(out nowMs);
                    global::WarriorsWeb.WebHost.Frame(nowMs);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnResize_1367123461(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __width_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __height_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                int width = default;
                int height = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __height_native.ToManaged(out height);
                    __width_native.ToManaged(out width);
                    global::WarriorsWeb.WebHost.OnResize(width, height);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnFocus_1344628367(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __focused_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                bool focused = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __focused_native.ToManaged(out focused);
                    global::WarriorsWeb.WebHost.OnFocus(focused);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnMouseMove_157530469(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __x_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __y_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                float x = default;
                float y = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __y_native.ToManaged(out y);
                    __x_native.ToManaged(out x);
                    global::WarriorsWeb.WebHost.OnMouseMove(x, y);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnScroll_157530469(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __dx_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __dy_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                float dx = default;
                float dy = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __dy_native.ToManaged(out dy);
                    __dx_native.ToManaged(out dx);
                    global::WarriorsWeb.WebHost.OnScroll(dx, dy);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnText_92020726(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __text_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                string text = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __text_native.ToManaged(out text);
                    global::WarriorsWeb.WebHost.OnText(text);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnClipboard_92020726(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __text_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                string text = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __text_native.ToManaged(out text);
                    global::WarriorsWeb.WebHost.OnClipboard(text);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnMouseButton_2140725032(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __down_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __jsButton_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                bool down = default;
                int jsButton = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __jsButton_native.ToManaged(out jsButton);
                    __down_native.ToManaged(out down);
                    global::WarriorsWeb.WebHost.OnMouseButton(down, jsButton);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
namespace WarriorsWeb
{
    public static unsafe partial class WebHost
    {
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static unsafe void __Wrapper_OnKey_571960800(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
        {
            __Stub(__arguments_buffer[2], __arguments_buffer[3], __arguments_buffer);
            [global::System.Diagnostics.DebuggerNonUserCode]
            void __Stub(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __down_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __code_native, global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* ____arg_exception_native__param)
            {
                bool down = default;
                string code = default;
                ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument ____arg_exception_native = ref *____arg_exception_native__param;
                try
                {
                    // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
                    __code_native.ToManaged(out code);
                    __down_native.ToManaged(out down);
                    global::WarriorsWeb.WebHost.OnKey(down, code);
                }
                catch (global::System.Exception __arg_exception)
                {
                    ____arg_exception_native.ToJS(__arg_exception);
                }
            }
        }
    }
}
