"""Builds the in-game music library (WaW-Server/Common/Resources/Config/Data/musicConfig.xml) from the audio files in WaW-Client/WaWClient/Content/Sound/Music.

The server plays this library on a shuffle for everybody; each track needs its length, so the tool measures every file with ffprobe. To add a song to the game:
drop the file into Content/Sound/Music, run this tool, rebuild and deploy (server AND clients: the clients need the audio file, the server needs this list).

The menu / title-screen music is NOT part of the in-game library: files whose name starts with one of MENU_PREFIXES are skipped, and so are a world's
own fixed tracks (WORLD_PREFIXES: Realm_*).
(Main_Music is the title-screen track today; a future Menu_Music file is skipped too.)

Run:  python Tools/Music/make_music_config.py
"""
import glob
import os
import re
import shutil
import subprocess
import sys
from xml.sax.saxutils import quoteattr

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')).replace(os.sep, '/') + '/'
MUSIC_DIR = ROOT + 'WaW-Client/WaWClient/Content/Sound/Music/'
OUT = ROOT + 'WaW-Server/Common/Resources/Config/Data/musicConfig.xml'
EXTENSIONS = ('.ogg', '.mp3', '.wav')
MENU_PREFIXES = ('main_music', 'menu_music')
WORLD_PREFIXES = ('realm_',)          # a world's own fixed music (the Realm plays Realm_* by itself, see InGameMusic.RealmTrack): never in the jukebox library


def find_ffprobe():
    found = shutil.which('ffprobe')
    if found:
        return found
    pattern = os.path.expandvars(r'%LOCALAPPDATA%\Microsoft\WinGet\Packages\Gyan.FFmpeg*\**\bin\ffprobe.exe')
    matches = glob.glob(pattern, recursive=True)
    if matches:
        return matches[0]
    sys.exit('ffprobe was not found (install ffmpeg, e.g. winget install Gyan.FFmpeg)')


def seconds(ffprobe, path):
    out = subprocess.check_output([ffprobe, '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', path]).decode().strip()
    return float(out)


def title(stem):
    words = re.sub(r'[_\-]+', ' ', stem).strip()
    return words[:1].upper() + words[1:]


def main():
    ffprobe = find_ffprobe()
    files = sorted(f for f in os.listdir(MUSIC_DIR) if f.lower().endswith(EXTENSIONS) and not f.lower().startswith(MENU_PREFIXES + WORLD_PREFIXES))
    if not files:
        sys.exit('no in-game tracks found in ' + MUSIC_DIR)

    lines = ['<MusicConfig>',
             '    <!-- The in-game music library, shuffled by the server for everybody. GENERATED by Tools/Music/make_music_config.py from Content/Sound/Music - run it after adding a song. -->']
    for f in files:
        stem = os.path.splitext(f)[0]
        length = seconds(ffprobe, MUSIC_DIR + f)
        lines.append('    <Track id=%s file=%s title=%s seconds="%.3f" />' % (quoteattr(stem), quoteattr(f), quoteattr(title(stem)), length))
        print('%-28s %7.1f s' % (f, length))
    lines.append('</MusicConfig>')
    open(OUT, 'w', encoding='utf-8', newline='\r\n').write('\r\n'.join(lines) + '\r\n')
    print('wrote', OUT, '(%d tracks)' % len(files))


if __name__ == '__main__':
    main()
