using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Common.Music;
using Common.Utilities;

namespace Common.Resources.Config;

// The in-game music library (Resources/Config/Data/musicConfig.xml, generated by Tools/Music/make_music_config.py).
public class MusicConfig {
    private const string ConfigFile = "Resources/Config/Data/musicConfig.xml";

    public MusicConfig(XElement e) {
        Tracks = e.Elements("Track")
            .Select(t => new MusicTrack(
                t.GetAttribute<string>("id"),
                t.GetAttribute<string>("file"),
                t.GetAttribute<string>("title"),
                (int)Math.Round(double.Parse(t.GetAttribute<string>("seconds"), System.Globalization.CultureInfo.InvariantCulture) * 1000)))
            .ToList();
    }

    public static MusicConfig Config
        => ConfigLoader<MusicConfig>.Load(ConfigFile, e => new MusicConfig(e));

    public IReadOnlyList<MusicTrack> Tracks { get; }
}
