"""Generates web/patched/*.cs from the desktop sources by applying small text patches (the desktop files are never edited),
and web/patched.props which removes the originals from the compile. Run before every web build (build.ps1 does).

RULES: (path relative to the repo root, [(old, new), ...]) - every 'old' must be found exactly once or the script fails
loudly, so an upstream change to a patched file is noticed instead of silently ignored.
More rules live in tools/patch_rules_more.py (exec'd below; it can call rule(path, (old, new), ...))."""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LT = os.path.normpath(os.path.join(HERE, '..', '..'))
WEB = os.path.join(LT, 'WebClient', 'web')
OUT = os.path.join(WEB, 'patched')

RULES = {}
FULL_REPLACE = {}   # rel path -> path of a hand-written replacement file (relative to WEB), used instead of patching


def rule(path, *pairs):
    RULES[path] = list(pairs)


def replace_file(path, replacement):
    FULL_REPLACE[path] = replacement


# Shared protocol: this file means System.Numerics.Vector2, the web build imports OpenTK.Mathematics globally.
rule('Shared/Common.Protocol/WorldPosData.cs', ('using System.Numerics;', 'using System.Numerics;\nusing Vector2 = System.Numerics.Vector2;'))

more = os.path.join(HERE, 'patch_rules_more.py')
if os.path.exists(more):
    exec(open(more, encoding='utf-8').read())

os.makedirs(OUT, exist_ok=True)
for f in os.listdir(OUT):
    if f.endswith('.cs'):
        os.remove(os.path.join(OUT, f))

removes = []
for rel, pairs in RULES.items():
    src = os.path.join(LT, *rel.split('/'))
    text = open(src, encoding='utf-8-sig', newline='').read().replace('\r\n', '\n')
    for pair in pairs:
        old, new = pair[0], pair[1]
        expect = pair[2] if len(pair) > 2 else 1
        n = text.count(old)
        if n != expect:
            sys.exit('PATCH FAILED: %s: expected %d matches, found %d for: %r' % (rel, expect, n, old[:70]))
        text = text.replace(old, new)
    name = rel.replace('/', '__')
    header = '// PATCHED COPY of %s (generated by tools/patch_sources.py - do not edit)\n' % rel
    open(os.path.join(OUT, name), 'w', encoding='utf-8', newline='\n').write(header + text)
    removes.append(rel)

for rel in FULL_REPLACE:
    removes.append(rel)   # the replacement is a normal file under web/shim; the original is just dropped

with open(os.path.join(WEB, 'patched.props'), 'w', encoding='utf-8') as p:
    p.write('<Project>\n  <!-- generated by tools/patch_sources.py -->\n  <ItemGroup>\n')
    for rel in removes:
        p.write('    <Compile Remove="$(MSBuildThisFileDirectory)../../%s" />\n' % rel)
    p.write('  </ItemGroup>\n</Project>\n')   # patched/*.cs is picked up by the SDK's default Compile glob
print('patched %d files, replaced %d' % (len(RULES), len(FULL_REPLACE)))
